### ISSUE TITLE
Add support to get Query Status

### ISSUE THREAD

**Issue by Cosmopal** [brotoo25/firestore-livedata#4]
Most use cases require the querying party to be aware of whether a query is loading, succeeded or failed. We can add support in this library so that the return type of the LiveData to be QueryStatus<T> instead of T. The QueryStatus is set to Loading on the first query, Succeeded on every successful fetch and failure if there is an exception

**Comment by brotoo25** [comment]
https://github.com/brotoo25/firestore-livedata/pull/6
