### ISSUE TITLE
Remove redundant classes

### ISSUE THREAD

**Issue by Cosmopal** [brotoo25/firestore-livedata#5]
Why does the library have XRaw, XNative and XCustom as separate classes?

Seems XRaw and XNative classes can be easily done away with by using XCustom with appropriate mapper function:

```
XRaw(...) = XCustom(..., {x -> x} )
XNative(..., clazz) = XCustom(..., {x - x.toObject(clazz) )
```

**Comment by brotoo25** [comment]
https://github.com/brotoo25/firestore-livedata/pull/6
